### ISSUE TITLE
August – September Correction Run

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/sk_general#1]
# August – September Correction Run

# FA Data

## Data enrichment
- [ ] FA - Add identifiers to listperson (ongoing)
- [x] FA - identify groups in listPers

### Entities
- [x] Persons
    - [x] Appellations: 
        - [x] `@subtype="pref"` need E55 Type https://sk.acdh.oeaw.ac.at/types/person/persname/pref - 
        see https://github.com/semantic-kraus/fa-data/issues/15
        - [x] `@subtype="pseud"` need E55 Type https://sk.acdh.oeaw.ac.at/types/person/persname/pseud - 
        see https://github.com/semantic-kraus/fa-data/issues/15
        - [x] If pref and pseud have the same string content, create only one Appellation with two E55 Types - 
        see https://github.com/semantic-kraus/fa-data/issues/15
        - [x] `@subtype="pref" and parent::person[sex/@value="male"]`:
        Add E55 Type https://sk.acdh.oeaw.ac.at/types/person/persname/male - 
        see https://github.com/semantic-kraus/fa-data/issues/15
        - [x] `@subtype="pref" and parent::person[sex/@value="female"]`:
        Add E55 Type https://sk.acdh.oeaw.ac.at/types/person/persname/female - 
        see https://github.com/semantic-kraus/fa-data/issues/15

- [x] Places:
    - [x] Appellations:
        - [x] Change <https://sk.acdh.oeaw.ac.at/types/place/placename> (is with every placename) to <https://sk.acdh.oeaw.ac.at/types/place/placename/pref> - see https://github.com/semantic-kraus/fa-data/issues/16
    - [x] Identifiers: Add PMB and Geonames-Identifiers (data is there) – see https://github.com/semantic-kraus/fa-data/issues/17
- [ ] Texts
    - [x] whole Fackel-Periodical: Add Appellation Date > AB
    - [x] whole Fackel-Periodical: URL-Identifier > AB
    - [x] Fackel issues: issue F22: add creation event w. reference to Kraus (as editor)
      - [ ] (Add type to these events: "issue editing")

### Relations
- [ ] Mentions
    - [x] Polish Segment location, add URL there > AB

# DW Data

## Data Enrichment
- [ ] DW - Add pmb-Identifiers to listplace

### Labels
- [ ] see https://github.com/semantic-kraus/dw-data/issues/16
### Entities
- [x] Identifiers - All Identifiers have rdfs:label w/ language tag `und`; should be `en` – see https://github.com/semantic-kraus/dw-data/issues/12
- [x] Occupations: All rdfs:label should be "de" – see https://github.com/semantic-kraus/dw-data/issues/12
- [ ] Persons
    - [x] Add Appellation with type <https://sk.acdh.oeaw.ac.at/types/person/persname/pref>
    - [x] Add Person Provenance: 
        - [x] 1 reference in E21 - see https://github.com/semantic-kraus/dw-data/issues/14
        - [x] 1 statement per source built separately in DW provenance graph
- [x] Places: Change Appellation type from <https://sk.acdh.oeaw.ac.at/types/place/placename/orig-name> to <https://sk.acdh.oeaw.ac.at/types/place/placename/pref> - see https://github.com/semantic-kraus/dw-data/issues/17
- [x] Groups: Change Appellation type from <https://sk.acdh.oeaw.ac.at/types/org/orgname/orig-name> to <https://sk.acdh.oeaw.ac.at/types/org/orgname/pref> - see https://github.com/semantic-kraus/dw-data/issues/17
- [ ] Texts
    - [ ] Appellations for F24 from `title[@level="j"]`, plus 1-2 E90 statements
    - [ ] (E30 Publication Events für @wholePeriodical)
    - [ ] (E52 TimeSpan für @wholePeriodical)
### Relations
- [x] Mentions
    - [x] Mention provenance
- [x] Relations DW-Intertext
    - [x] Fix [n]-Problem with bibl containing a wholeText-citedRage 
- [ ] Relations Intertext-Intertext
    - [ ] Dito

# LK Data

## Data Enrichment
- [x]
### Entities
- [x] Persons: Add Appellation with type <https://sk.acdh.oeaw.ac.at/types/person/persname/pref> – see https://github.com/semantic-kraus/lk-data/issues/94
- [x] Places: Add Appellation with type <https://sk.acdh.oeaw.ac.at/types/place/placename/pref> – see https://github.com/semantic-kraus/lk-data/issues/109
- Texts
    - [x] Legal docs
        - [x] Creation event, Creator, Time
        - [x] Identifier
        - [x] Title
    - [x] works from listwork
        - [x] clean labels for F22

### Relations
- [x] Mentions
- [x] LK - Intertextual Relations - quotes: 
  - [x] Die Fackel: `quote[starts-with(@source, "https://fackel")]` - awaiting https://github.com/semantic-kraus/lk-data/issues/66
  - listwork:
    - [x] INT3 Intertextual Relation should aim at a Text Passage, not whole Text, like with all the other quotes. See https://github.com/semantic-kraus/lk-data/issues/93
    - [x] some missing segments – see https://github.com/semantic-kraus/dw-data/issues/18
  - [x] legal doc
- [x] LK - Intertextual Relations - `note[@type="intertext"]` - see https://github.com/semantic-kraus/lk-data/issues/66
- [x] LK - Intertextual Relations: rs
  - [x] "Die Fackel" `rs[@subtype="fackel"]`
  - [x] legal doc `rs[@subtype="legal-doc"]`
  - [x] listwork `rs[@subtype="pmb"]`

# SK General

## Metadata, Cross-Dataset
- [x] Add inverse Triples – see https://github.com/semantic-kraus/lk-data/issues/89
- [ ] Add owl:sameAs relations
- [x] rdfs:label rules: 'pure values' for E21 (person name), E53 (place name), E52 (time span), group (group name), F22 (title), E73 (title)
- Change all data to .trig
    - [x] persons (fa-data) – see https://github.com/semantic-kraus/fa-data/issues/13
    - [x] texts
    - [x] mentions
- [x] Check all namespaces
- Add data provenance to all graphs
    - [ ] FA
    - [ ] LK
    - [ ] DW
    - [ ] General
- [x] Add metadata (rdfs:comments) to E55 Types
- [x] Add missing/implicit inverse relations to sk_model.owl
- [x] Add isDefinedIn properties to sk_model.owl (low priority)
